require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IntranetsController do

  # This should return the minimal set of attributes required to create a valid
  # Intranet. As you add validations to Intranet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "category_name" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IntranetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all intranets as @intranets" do
      intranet = Intranet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:intranets).should eq([intranet])
    end
  end

  describe "GET show" do
    it "assigns the requested intranet as @intranet" do
      intranet = Intranet.create! valid_attributes
      get :show, {:id => intranet.to_param}, valid_session
      assigns(:intranet).should eq(intranet)
    end
  end

  describe "GET new" do
    it "assigns a new intranet as @intranet" do
      get :new, {}, valid_session
      assigns(:intranet).should be_a_new(Intranet)
    end
  end

  describe "GET edit" do
    it "assigns the requested intranet as @intranet" do
      intranet = Intranet.create! valid_attributes
      get :edit, {:id => intranet.to_param}, valid_session
      assigns(:intranet).should eq(intranet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Intranet" do
        expect {
          post :create, {:intranet => valid_attributes}, valid_session
        }.to change(Intranet, :count).by(1)
      end

      it "assigns a newly created intranet as @intranet" do
        post :create, {:intranet => valid_attributes}, valid_session
        assigns(:intranet).should be_a(Intranet)
        assigns(:intranet).should be_persisted
      end

      it "redirects to the created intranet" do
        post :create, {:intranet => valid_attributes}, valid_session
        response.should redirect_to(Intranet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved intranet as @intranet" do
        # Trigger the behavior that occurs when invalid params are submitted
        Intranet.any_instance.stub(:save).and_return(false)
        post :create, {:intranet => { "category_name" => "invalid value" }}, valid_session
        assigns(:intranet).should be_a_new(Intranet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Intranet.any_instance.stub(:save).and_return(false)
        post :create, {:intranet => { "category_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested intranet" do
        intranet = Intranet.create! valid_attributes
        # Assuming there are no other intranets in the database, this
        # specifies that the Intranet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Intranet.any_instance.should_receive(:update).with({ "category_name" => "MyText" })
        put :update, {:id => intranet.to_param, :intranet => { "category_name" => "MyText" }}, valid_session
      end

      it "assigns the requested intranet as @intranet" do
        intranet = Intranet.create! valid_attributes
        put :update, {:id => intranet.to_param, :intranet => valid_attributes}, valid_session
        assigns(:intranet).should eq(intranet)
      end

      it "redirects to the intranet" do
        intranet = Intranet.create! valid_attributes
        put :update, {:id => intranet.to_param, :intranet => valid_attributes}, valid_session
        response.should redirect_to(intranet)
      end
    end

    describe "with invalid params" do
      it "assigns the intranet as @intranet" do
        intranet = Intranet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Intranet.any_instance.stub(:save).and_return(false)
        put :update, {:id => intranet.to_param, :intranet => { "category_name" => "invalid value" }}, valid_session
        assigns(:intranet).should eq(intranet)
      end

      it "re-renders the 'edit' template" do
        intranet = Intranet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Intranet.any_instance.stub(:save).and_return(false)
        put :update, {:id => intranet.to_param, :intranet => { "category_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested intranet" do
      intranet = Intranet.create! valid_attributes
      expect {
        delete :destroy, {:id => intranet.to_param}, valid_session
      }.to change(Intranet, :count).by(-1)
    end

    it "redirects to the intranets list" do
      intranet = Intranet.create! valid_attributes
      delete :destroy, {:id => intranet.to_param}, valid_session
      response.should redirect_to(intranets_url)
    end
  end

end
